GenPart_momFirstCopy:
    name: GenPart_momPrompt
    path: GEM.Modules.GenPart_momPrompt
    parameters:
        isDY: self.dataset.process.get_aux('isDY', False)

DY_TauStitching:
    name: DY_TauDecay
    path: GEM.Modules.Sample_Overlapping
    parameters:
        isDY: self.dataset.process.get_aux('isDY', False)

DY_MassStitching:
    name: DY_MassOverlapping
    path: GEM.Modules.Sample_Overlapping
    parameters:
        isFirstMbin: self.dataset.process.get_aux('isFirstMbin', False)

DY_HTStitching:
    name: DY_HTOverlapping
    path: GEM.Modules.Sample_Overlapping
    parameters:
        isHTbin: self.dataset.process.get_aux('isHTbin', False)

TTbar_Stitching:
    name: TTbar_Overlapping
    path: GEM.Modules.Sample_Overlapping
    parameters:
        isTT: self.dataset.process.get_aux('isTT', False)

DiMuon_Selector:
    name: DiMuonSelec
    path: GEM.Modules.DiMuonSelec