puweight:
    name: puWeightRDF
    path: Corrections.LUM.puWeight
    parameters:
        isMC: self.dataset.process.isMC
        year: self.config.year
        isUL: self.dataset.has_tag('ul')

Muon_SFs:
    name: MuonSF
    path: Corrections.MUO.muonSF_GEMethod
    parameters:
        isMC: self.dataset.process.isMC
        year: self.config.year
        isUL: self.dataset.has_tag('ul')
        preVFP: self.dataset.has_tag('preVFP')

ptZ reweight:
    name: ptZreweightRDF
    path: GEM.Modules.ptZreweight
    parameters:
        isMC: self.dataset.process.isMC
        year: self.config.year
        isUL: self.dataset.has_tag('ul')
        preVFP: self.dataset.has_tag('preVFP')

kappa regions:
    name: biasRegions
    path: GEM.Modules.biasMap_regions